### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-singleton-bacha-chat-tp5#1]
Hello,

- [ ] La définition d'un Bean Spring n'est pas assez complète et il manque la définition du contexte

- [ ] La définition de l'autowiring n'est pas bonne. Sachez qu'on peut faire de l'autowiring en configuration XML. Je vous laisse trouver comment et me l'expliquer ici.

- Good Job pour la configuration SpringBoot. J'espère que maintenant vous arrivez à mieux cerner ce qu'est Spring?

**Comment by TheCaptainCat** [comment]
Bonjour,

* Spring est un conteneur fonctionnant sur le principe de l’inversion de contrôle. C'est Spring qui va charger l'application et instancier les différents composants. Un Bean est un composant Spring (la graine et la tige... tjrs plein d'humour les nerds). Les Beans sont déclarés dans un fichier XML ou grâce à des annotations. Afin de les instancier, on n'appelle pas directement le constructeur.

```java
private final ApplicationContext context;

@Autowired
public DemoApplication(ApplicationContext context) {
    this.context = context;
}

...
    context.getBean(Cat.class, "Garfield")
....
```

Ici, `Cat` est un `@Component`, et Spring va l'instancier et passer les paramètres au constructeur. Ici, on appelle le contexte de l'application. C'est là que se trouvent toutes les configurations que Spring a chargé depuis le code.

Avec une configuration XML, on utilise :
```java
BeanFactory beanFactory = new ClassPathXmlApplicationContext("spring-config.xml");
beanFactory.getBean(Cat.class, "Garfield")
```

* L'autowiring demande à Spring de charger automatiquement un Bean s'il n'en existe qu'un seul de ce type. Dans notre exemple, le constructeur de `DemoApplication` est autowired. Spring va y injecter le contexte de l'application.
Dans le projet, `Loggable` contient un `Logger` autowired. Il existe deux implémentations de `Logger`. Elles sont déclarées dans la classe principale.

```java
@Profile("console")
@Bean
public Logger consoleLogger() {
    return new ConsoleLogger();
}

@Profile("file")
@Bean
public Logger fileLogger() {
    return new FileLogger();
}
```

Deux Beans déclarent le même type. C'est pour ça que nous utilisons les profils. Simplement en changeant le profil par défaut dans `application.properties`, ou en argument de lancement, l'autowiring va charger l'un ou l'autre des `Logger`.

**Comment by Slashgear** [comment]
Ok cool, ça me va. Sachez également que l'autowiring peut se faire en se basant sur le nom du Bean et pas uniquement sur le type.
